# Site Info
title: Lanyon
tagline: 'A Jekyll theme'
description: 'A reserved <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
baseurl: "/lanyon"
url: http://lanyon.getpoole.com

paginate: 5
paginate_path: '/blog/page:num'
permalink: pretty

# About/contact
author:
  name: Codinfox
  description: A passionate <strong>developer and researcher</strong>, learning to be a giant.
  gravatar: 3c2986ad7ac1f2230ea3596f44563328 # md5 hash of your email address
  contact:
    linkedin:  https://www.linkedin.com/in/lizhihao
    github:    https://github.com/codinfox
    # facebook:  <hide>
    twitter:   https://twitter.com/Li_Zhihao
    weibo:     http://weibo.com/41173780
    email:     http://www.google.com/recaptcha/mailhide/d?k=01I3lZFiZYng9N3QxYEtsDaQ==&c=31wAnZkuKqcG0ATAqJN8Z3ln5kkYLA9TwkGc-IbygpM=

# Navigation
nav:
  Home:           '/'
  Blog:           '/blog/'
  About:          '/about/'
  Github Project: 'http://github.com/'


  # Custom vars
version: 1.0.0

gems:
  - jekyll-paginate

markdown: kramdown
kramdown:
  input: GFM

sass:
  style: compressed
  sass_dir: _scss    
